### ISSUE TITLE
Race condition - two connections trying to create a Stream at the same time

### ISSUE THREAD

**Issue by juliev0** [nats-io/nats.go#949]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
github.com/nats-io/nats.go v1.13.1-0.20220308171302-2f2f6968e98d

nats server docker container: nats:2.7.4

#### OS/Container environment:
Kubernetes, nats server docker container: nats:2.7.4

#### Steps or code to reproduce the issue:

2 clients create a connection
At the **same time** they each call AddStream() on their separate connections.
`streamConfig := nats.StreamConfig{
		Name:     "default",
		Subjects: []string{"default.*.*"},
		Storage:  nats.FileStorage,
		Replicas: 3,
	}

	_, err = conn.JSContext.AddStream(&streamConfig)
	if err != nil {
		panic(fmt.Sprintf("Failed to add Jetstream stream: %v for connection %+v", err, conn))
	}`

#### Expected result:
One should succeed in creating the Stream. The other should not create the Stream but not error out.

#### Actual result:
One client creates the Stream. The other client gets the error "context deadline exceeded" after 5 seconds.

I am attaching Trace level logs. 
The timestamps are approximately:
2022-04-06T20:04:17.3: First connection successfully creates stream 
2022-04-06T20:04:17.3: Second connection attempts to create stream
2022-04-06T20:04:22.3: Second connection returns "context deadline exceeded"

[jetstream2.log](https://github.com/nats-io/nats.go/files/8430236/jetstream2.log)
[jetstream0.log](https://github.com/nats-io/nats.go/files/8430237/jetstream0.log)
[jetstream1.log](https://github.com/nats-io/nats.go/files/8430238/jetstream1.log)

**Comment by rohsaini** [comment]
Hi,
Any update on this?

Thanks.

**Comment by derekcollison** [comment]
This has been fixed in the server, try running against server version 2.9.9.

**Comment by rohsaini** [comment]
I tried with 2.9.9, I still see the problem where same stream twice is getting created from two connections. StreamConfig is same for both. Attaching logs.

[stream_create_issue.docx](https://github.com/nats-io/nats.go/files/10224364/stream_create_issue.docx)

**Comment by derekcollison** [comment]
What do you mean same stream is being created? That call is idempotent, so one will win and create the stream and one will return the existing stream as long as configs are exactly the same.

The bug with timeout when server would not answer second concurrent request is what was fixed.
